"""
email_service.py
----------------
Sends container risk investigation reports via email (SMTP).
"""

import smtplib
import os
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

logger = logging.getLogger(__name__)


def send_report_email(
    to_email: str,
    container_id: str,
    risk_level: str,
    risk_score: float,
    pdf_bytes: bytes,
    ai_summary: str | None = None,
) -> dict:
    """
    Send a PDF investigation report via SMTP.

    Required env vars: SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD
    Optional: ai_summary — short AI explanation included in the email body.
    Returns dict with 'success' bool and 'message' str.
    """
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")

    if not smtp_user or not smtp_pass:
        return {
            "success": False,
            "message": "Email service not configured. Set SMTP_USER and SMTP_PASSWORD environment variables."
        }

    msg = MIMEMultipart()
    msg["From"] = smtp_user
    msg["To"] = to_email
    msg["Subject"] = f"Container Risk Investigation Report — {container_id}"

    ai_section = ""
    if ai_summary:
        ai_section = f"\n\nAI Intelligence Summary\n{'-'*40}\n{ai_summary}\n"

    body = f"""Container Risk Investigation Report

Container ID: {container_id}
Risk Score: {risk_score:.1f}/100
Risk Level: {risk_level}
{ai_section}
Please find the detailed investigation report attached.

This is an automated report generated by the SmartContainer Risk Engine.
"""
    msg.attach(MIMEText(body, "plain"))

    # Attach PDF
    attachment = MIMEBase("application", "octet-stream")
    attachment.set_payload(pdf_bytes)
    encoders.encode_base64(attachment)
    attachment.add_header(
        "Content-Disposition",
        f"attachment; filename=container_report_{container_id}.pdf",
    )
    msg.attach(attachment)

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        logger.info(f"Report email sent to {to_email} for container {container_id}")
        return {"success": True, "message": f"Report sent to {to_email}"}
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return {"success": False, "message": f"Failed to send email: {str(e)}"}
